name: Docker Image CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomsik68/xampp:8.0.2
          build-args:
            - XAMPP_URL=https://www.apachefriends.org/xampp-files/8.0.2/xampp-linux-x64-8.0.2-0-installer.run?from_af=true

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomsik68/xampp:7.3.7,tomsik68/xampp:7
          build-args:
            - XAMPP_URL=https://www.apachefriends.org/xampp-files/7.3.7/xampp-linux-x64-7.3.7-1-installer.run?from_af=true

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomsik68/xampp:5.6.28,tomsik68/xampp:5
          build-args:
            - XAMPP_URL=https://www.apachefriends.org/xampp-files/5.6.28/xampp-linux-x64-5.6.28-1-installer.run?from_af=true
